name: tests

on:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run unit tests and doctests
        run: cargo test

      - name: Fetch assets for integration tests
        run: ./tests/setup.sh
      
      - name: Run integration tests
        run: cargo test --features tests --no-fail-fast